[gitInfo]
  dir = "content/zh-cn"

[search]
  [search.algolia]
    index = "index.zh-cn"



[home]
  paginate = 10
  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/avatar.jpg"
    avatarMenu = ""
    title = "xiix"
    subtitle = "爱做奇特键盘的程序员"
    typeit = true
    social = true
    disclaimer = ""
  [home.posts]
    enable = true
    paginate = 6   